from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent

DATASET_CONFIG = {
    "DATA_DIR": PROJECT_ROOT / "data" / "ofc-2026-ml-challenge",
    "TRAIN_FEATURES_PATH": PROJECT_ROOT / "data" / "ofc-2026-ml-challenge" / "train_features_clean.csv",
    "TRAIN_LABELS_PATH": PROJECT_ROOT / "data" / "ofc-2026-ml-challenge" / "train_labels_clean.csv",
    "TEST_FEATURES_PATH": PROJECT_ROOT / "data" / "ofc-2026-ml-challenge" / "test_features.csv",
    "COSMOS_DATA_DIR": PROJECT_ROOT / "data" / "cosmos-as-kaggle",
    "COSMOS_TRAIN_FEATURES_PATH": PROJECT_ROOT / "data" / "cosmos-as-kaggle" / "train_features.csv",
    "COSMOS_TRAIN_LABELS_PATH": PROJECT_ROOT / "data" / "cosmos-as-kaggle" / "train_labels.csv",
    "DATASET_USE": "both",
    "RANDOM_STATE": 42,
    "TEST_SIZE": 0.05,
}

OUTPUT_CONFIG = {
    "SUBMISSION_DIR": PROJECT_ROOT / "submissions",
}

FEATURE_CONFIG = {
    "USE_MASK": "multiply", # concat, multiply, none
}

MODEL_CONFIG = {
    "DROPOUT": 0.2,
    "HIDDEN_DIMS": [256, 256, 128, 128, 128],
    "N_FREQUENCIES": 4,
    "SPECTRAL_FREQ_RATIO": 0.5,
    "USE_SPECTRAL_MIXING": True,
}

TRAINING_CONFIG = {
    "DEVICE": "cuda",
    "LOAD_PRETRAINED_MODEL": True,
    "PRETRAIN_MODEL_PATH": PROJECT_ROOT / "models" / "pretrained_model_zyk_0123_01_multiply.pt",
    "USE_MIXED_PRECISION": True,  # 使用混合精度训练（FP16）
}

PRETRAIN_CONFIG = {
    "LEARNING_RATE": 0.001,
    "WEIGHT_DECAY": 1e-4,
    "BATCH_SIZE": 256,
    "EPOCHS": 500,
    "EARLY_STOPPING_PATIENCE": 40,
    "VAL_EVERY_N_EPOCHS": 2,  # 每2个epoch验证一次
}

FINETUNE_CONFIG = {
    "LEARNING_RATE": 0.0002,
    "WEIGHT_DECAY": 5e-5,
    "BATCH_SIZE": 64,
    "EPOCHS": 500,
    "EARLY_STOPPING_PATIENCE": 60,
    "DISCRIMINATIVE_LR_DECAY": 0.95,
    "VAL_EVERY_N_EPOCHS": 1,  # 微调阶段每个epoch验证
}

DATA_DIR = DATASET_CONFIG["DATA_DIR"]
TRAIN_FEATURES_PATH = DATASET_CONFIG["TRAIN_FEATURES_PATH"]
TRAIN_LABELS_PATH = DATASET_CONFIG["TRAIN_LABELS_PATH"]
TEST_FEATURES_PATH = DATASET_CONFIG["TEST_FEATURES_PATH"]
COSMOS_DATA_DIR = DATASET_CONFIG["COSMOS_DATA_DIR"]
COSMOS_TRAIN_FEATURES_PATH = DATASET_CONFIG["COSMOS_TRAIN_FEATURES_PATH"]
COSMOS_TRAIN_LABELS_PATH = DATASET_CONFIG["COSMOS_TRAIN_LABELS_PATH"]
DATASET_USE = DATASET_CONFIG["DATASET_USE"]
RANDOM_STATE = DATASET_CONFIG["RANDOM_STATE"]
TEST_SIZE = DATASET_CONFIG["TEST_SIZE"]

SUBMISSION_DIR = OUTPUT_CONFIG["SUBMISSION_DIR"]

USE_MASK = FEATURE_CONFIG["USE_MASK"]

HYBRID_FNO_KAN_DROPOUT = MODEL_CONFIG["DROPOUT"]
HYBRID_FNO_KAN_HIDDEN_DIMS = MODEL_CONFIG["HIDDEN_DIMS"]
HYBRID_FNO_KAN_N_FREQUENCIES = MODEL_CONFIG["N_FREQUENCIES"]
HYBRID_FNO_KAN_SPECTRAL_FREQ_RATIO = MODEL_CONFIG["SPECTRAL_FREQ_RATIO"]
HYBRID_FNO_KAN_USE_SPECTRAL_MIXING = MODEL_CONFIG["USE_SPECTRAL_MIXING"]

DEVICE = TRAINING_CONFIG["DEVICE"]
LOAD_PRETRAINED_MODEL = TRAINING_CONFIG["LOAD_PRETRAINED_MODEL"]
PRETRAIN_MODEL_PATH = TRAINING_CONFIG["PRETRAIN_MODEL_PATH"]
USE_MIXED_PRECISION = TRAINING_CONFIG.get("USE_MIXED_PRECISION", False)

PRETRAIN_LEARNING_RATE = PRETRAIN_CONFIG["LEARNING_RATE"]
PRETRAIN_WEIGHT_DECAY = PRETRAIN_CONFIG["WEIGHT_DECAY"]
PRETRAIN_BATCH_SIZE = PRETRAIN_CONFIG["BATCH_SIZE"]
PRETRAIN_EPOCHS = PRETRAIN_CONFIG["EPOCHS"]
PRETRAIN_EARLY_STOPPING_PATIENCE = PRETRAIN_CONFIG["EARLY_STOPPING_PATIENCE"]
PRETRAIN_VAL_EVERY_N_EPOCHS = PRETRAIN_CONFIG.get("VAL_EVERY_N_EPOCHS", 1)

FINETUNE_LEARNING_RATE = FINETUNE_CONFIG["LEARNING_RATE"]
FINETUNE_WEIGHT_DECAY = FINETUNE_CONFIG["WEIGHT_DECAY"]
FINETUNE_BATCH_SIZE = FINETUNE_CONFIG["BATCH_SIZE"]
FINETUNE_EPOCHS = FINETUNE_CONFIG["EPOCHS"]
FINETUNE_EARLY_STOPPING_PATIENCE = FINETUNE_CONFIG["EARLY_STOPPING_PATIENCE"]
FINETUNE_VAL_EVERY_N_EPOCHS = FINETUNE_CONFIG.get("VAL_EVERY_N_EPOCHS", 1)
DISCRIMINATIVE_LR_DECAY = FINETUNE_CONFIG["DISCRIMINATIVE_LR_DECAY"]
