_wandb:
    value:
        cli_version: 0.23.1
        e:
            mka8zu7r2jmjo2zf0hgqin7fgnw0ys58:
                apple:
                    ecpuCores: 4
                    gpuCores: 19
                    memoryGb: 32
                    name: Apple M2 Pro
                    pcpuCores: 8
                    ramTotalBytes: "34359738368"
                    swapTotalBytes: "17179869184"
                codePath: main.py
                codePathLocal: main.py
                cpu_count: 12
                cpu_count_logical: 12
                disk:
                    /:
                        total: "494384795648"
                        used: "369569996800"
                email: zhuyukang2000@gmail.com
                executable: /opt/miniconda3/envs/ofc/bin/python
                git:
                    commit: c800c6efda1be848a7e746bcfa99236348de6c0d
                    remote: https://github.com/yukangZhuu/ofc_ml.git
                host: CWDN2Y70WP
                memory:
                    total: "34359738368"
                os: macOS-14.7.8-arm64-arm-64bit
                program: /Users/bytedance/Documents/ofc_ml/main.py
                python: CPython 3.12.12
                root: /Users/bytedance/Documents/ofc_ml
                startedAt: "2026-01-11T15:00:31.769799Z"
                writerId: mka8zu7r2jmjo2zf0hgqin7fgnw0ys58
        m: []
        python_version: 3.12.12
        t:
            "1":
                - 1
                - 5
                - 53
            "2":
                - 1
                - 5
                - 53
            "3":
                - 1
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.12.12
            "5": 0.23.1
            "12": 0.23.1
            "13": darwin-arm64
T_0:
    value: 20
T_mult:
    value: 2
batch_size:
    value: 64
device:
    value: cpu
epochs:
    value: 100
eta_min:
    value: 1e-06
input_dim:
    value: 207
learning_rate:
    value: 0.0005
num_cat:
    value: 13
num_mask:
    value: 95
num_scalar:
    value: 4
num_spectral:
    value: 95
optimizer:
    value: AdamW
output_dim:
    value: 95
patience:
    value: 30
random_state:
    value: 42
scheduler:
    value: CosineAnnealingWarmRestarts
train_samples:
    value: 490
val_samples:
    value: 98
weight_decay:
    value: 0.0001
